FROM python:3.6-alpine
COPY . /srv/cartao-visita
# VOLUME /srv/cartao-visita
EXPOSE 8000

WORKDIR /srv/cartao-visita

RUN apk update \
    && apk upgrade \
    && apk add --no-cache build-base libffi-dev libxslt-dev libxml2-dev cairo-dev libjpeg-turbo-dev unixodbc-dev \
		&& pip install --no-cache-dir -r requirements.txt

CMD ["gunicorn", "--workers", "2", "--bind", "0.0.0.0:8000", "wsgi:app"]